### ISSUE TITLE
feat: add TestLessThanOrEqualAddress

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/cairo-vm-ts#122]
Estimated time: 0.5d
Lifespan: 1d

- Implement the [TestLessThanOrEqualAddress hint](https://github.com/starkware-libs/cairo/blob/c26d49f87c422949215a07eb2ee6d7a69c14bd84/crates/cairo-lang-casm/src/hints/mod.rs#L127-L129).
- Add unit tests, testing the parsing and the logic of the hint.
- Add a Cairo program using the hint, used as an integration test .

How-to implement a hint on the Cairo VM TS available [here](https://github.com/kkrt-labs/cairo-vm-ts/blob/main/docs/howToImplementAHint.md)

Similar to the TestLessThanOrEqual hint, but expecting Relocatable instead of Felt.
[Rust implementation reference of TestLessThanOrEqual](https://github.com/lambdaclass/cairo-vm/blob/41476335884bf600b62995f0c005be7d384eaec5/vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs#L331-L344)

**Comment by renzobanegass** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hey, I'm Renzo, a Software Engineer with over 5 years of experience, I recently started contributing to Web3 as a member of Dojo Coding, I have contributed in languages like Cairo and Rust already.

### How I plan on tackling this issue
1. Review Documentation and References
2. Implement the Hint in Cairo VM TS
Referencing the Rust implementation and the guide on implementing hints, create the new hint.
3. Add Unit Tests
4. Create Integration Test in Cairo
5. Run Tests and Verify Implementation
7. Submit PR

**Comment by zmalatrax** [comment]
Sure, assigned

**Comment by renzobanegass** [comment]
Hi, I have a question about the implementation of the hint, as there's no example for this one, 

```
export const testLessThanOrEqualAddress = (
  vm: VirtualMachine,
  lhs: ResOperand,
  rhs: ResOperand,
  dst: CellRef
) => {
  const lhsValue = vm.getResOperandValue(lhs);
  const rhsValue = vm.getResOperandValue(rhs);
  const result = new Felt(BigInt(lhsValue <= rhsValue));
  vm.memory.assertEq(vm.cellRefToRelocatable(dst), result);
};
```

This implementation is quite similar to how the TestLessThanOrEqual hint would be, what I'm not sure about is, the result should be a Relocatable? If so, how can I do that conversion?  If not, should the inputs be a Relocatable? I didn't quite get that part. Thank you!

**Comment by zmalatrax** [comment]
> Hi, I have a question about the implementation of the hint, as there's no example for this one,

Hi, indeed missed providing the right one, here is a proper [reference](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/casm_run/mod.rs#L1667-L1674).

This hint was actually introduced with [Cairo 2.7.0](https://github.com/starkware-libs/cairo/releases/tag/v2.7.0) and the `multi_pop_back()`/`multi_pop_front()` methods in this [PR](https://github.com/starkware-libs/cairo/pull/5588). 

I'm currently bumping the Cairo compiler submodule to the right version so you can write and compile a Cairo program using this hint.

>This implementation is quite similar to how the TestLessThanOrEqual hint would be, what I'm not sure about is, the result should be a Relocatable? If so, how can I do that conversion? If not, should the inputs be a Relocatable? I didn't quite get that part. Thank you! 

Yes the inputs should be `Relocatable`, while the result is a `Felt`. It means that `lhsValue` and  `rhsValue` extracted from `lhs` and `rhs` are expected to be `Relocatable` rather than `Felt` as in TestLessThanOrEqual.

The current method handling `ResOperand` is `getResOperandValue()` and only extracts `Felt` and not `Relocatable`.

I'll update the API so that you can properly implement the `TestLessThanOrEqualAddress` :)

**Comment by zmalatrax** [comment]
@renzobanegass All good now, you can use `vm.getResOperandRelocatable()` to extract a Relocatable from a ResOperand :)

**Comment by renzobanegass** [comment]
Great, I'll get to it then!

**Comment by renzobanegass** [comment]
Does this implementation look better?

```
export const testLessThanOrEqualAddress = (
  vm: VirtualMachine,
  lhs: ResOperand,
  rhs: ResOperand,
  dst: CellRef
) => {
  const lhsValue = vm.getResOperandRelocatable(lhs);
  const rhsValue = vm.getResOperandRelocatable(rhs);

  const isLessThanOrEqual = lhsValue.segmentId < rhsValue.segmentId || 
                            (lhsValue.segmentId === rhsValue.segmentId && lhsValue.offset <= rhsValue.offset);
                            
  const result = new Felt(isLessThanOrEqual ? 1n : 0n);

  vm.memory.assertEq(vm.cellRefToRelocatable(dst), result);
};
```

**Comment by zmalatrax** [comment]
> Does this implementation look better?

Open a PR, I'll make a review, it'll be much easier
