### ISSUE TITLE
feat: add DivMod hint

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/cairo-vm-ts#125]
Estimated time: 0.5d
Lifespan: 1d

- Implement the [DivMod hint](https://github.com/starkware-libs/cairo/blob/c26d49f87c422949215a07eb2ee6d7a69c14bd84/crates/cairo-lang-casm/src/hints/mod.rs#L134-L138).
- Add unit tests, testing the parsing and the logic of the hint.
- Add a Cairo program using the hint, used as an integration test .

How-to implement a hint on the Cairo VM TS available [here](https://github.com/kkrt-labs/cairo-vm-ts/blob/main/docs/howToImplementAHint.md)

[Rust implementation reference](https://github.com/lambdaclass/cairo-vm/blob/41476335884bf600b62995f0c005be7d384eaec5/vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs#L410-L425)

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I'm a software developer with 2+ years of experience and I'm member of Dojo Coding community here in CR and I have made contributions in Cairo VM Go, some days ago I implemented a hint there.

### How I plan on tackling this issue
This will be my approach:

1. Review Documentation and References: Understand the hint requirements and analyze existing implementations.
2. Plan and Design the Implementation: Reference Rust and Cairo implementations.
3. Implement the Hint in Cairo VM TS: Write the hint code following project guidelines.
4. Add Unit Tests: Create unit tests to validate the hint implementation.
5. Create Integration Tests: Develop integration tests to verify functionality within the system.
6. Run Tests and Verify Implementation: Execute all tests to ensure correctness.
7. Submit PR: Submit my pull request with a clear description and request feedback.

Thanks.

**Comment by zmalatrax** [comment]
Sure, assigned
