### ISSUE TITLE
dev: implement Montgomery representation for Felt

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/cairo-vm-ts#5]
In order to perform efficient arithmetic operations on the Felt primitive type, implement the [Montgomery representation](https://cryptography.fandom.com/wiki/Montgomery_reduction) of it.

**Comment by Eikix** [comment]
could it be better to try and use felt from lambdaworks?

**Comment by Eikix** [comment]
or even felt from type-rs

**Comment by Eikix** [comment]
https://github.com/starknet-io/types-rs/pull/4

**Comment by greged93** [comment]
So we would wasm it and use it here? Sounds good to me

**Comment by Eikix** [comment]
de-prioritizing this in favor of readability
