### ISSUE TITLE
test: make direct use of builtin pointer rather than built-in cairo functions 

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/cairo-vm-ts#64]
As suggested by Clement in a comment of #62, cairo program to test bitwise could directly use the builtin pointer.

- Cleanup the *.cairo test files
- Simplify the bitwise cairo test program to directly use `bitwise_ptr`
- For future builtin integration tests, directly use the builtin pointer for simple tests

**Comment by danielcdz** [comment]
Hello @zmalatrax I want to help with this one! In the past I made contributions to the Cairo-vm-go from nethermind

**Comment by zmalatrax** [comment]
Hi @danielcdz,  assigned

**Comment by danielcdz** [comment]
Hey @zmalatrax, I created a draft [pr](https://github.com/kkrt-labs/cairo-vm-ts/pull/73), I'm a little confused and I want to know if I'm following the right path, feel free to add any suggestion!
