### ISSUE TITLE
feat: implement RangeCheck builtin

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/cairo-vm-ts#68]

**Comment by coxmars** [comment]
Hi, @zmalatrax ,

I would like to help with this one if it hasn't been assigned yet. I have studied CairoVM, the Cairo whitepaper, and have created documentation for CairoVM Go, so I am well-versed in its implementation. Here’s my plan:

- Analyze the requirements for the RangeCheck builtin and understand its usage within the Cairo ecosystem.
- Implement the RangeCheck builtin in Cairo, ensuring it integrates seamlessly in the existent code.
- Document the implementation to assist future developers in understanding and using the RangeCheck builtin effectively.
- I am confident I can complete this task within 4 days.

Thanks!

**Comment by ClementWalter** [comment]
@coxmars please joined the newly created tg group https://t.me/cairovmts when can you start working on this?
