### ISSUE TITLE
feat: implement Pedersen builtin

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/cairo-vm-ts#70]

**Comment by jimenezz22** [comment]
Hi, @zmalatrax 

I would like to help with this issue. I have studied CairoVM and helped create documentation for cairo-vm-go at Nethermind. You can see my contribution here: https://github.com/NethermindEth/cairo-vm-go/pull/379#pullrequestreview-2073425276

- Examine the requirements for the Pedersen builtin and understand its role within the Cairo ecosystem.
- Implement the Pedersen builtin in Cairo, ensuring seamless integration with the existing code.
- Document the implementation to aid future developers in understanding and effectively using the Pedersen builtin.

Thank you!
